# https://golangci-lint.run/usage/configuration/
version: "2"
run:
  timeout: 3m
linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
linters-settings:
  govet:
    enable:
      - nilness
